In [205]:
import numpy as np

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

# create an array of integers
# input_maze = np.array([[0,0,0],[1,1,0],[0,0,0]])
input_maze = np.array([[0,0,1,1,0,0,0,0],
                      [1,0,0,0,0,0,1,1],
                      [1,1,1,1,1,0,1,1],
                      [1,1,1,1,1,0,1,1],
                      [1,0,0,0,0,0,1,1],
                      [1,0,1,1,1,1,1,1],
                      [1,0,0,0,0,0,0,0],
                      [1,1,1,1,1,1,1,1]])
#input_maze = np.array([[0,0,0,0],[1,0,1,1],[1,0,0,0],[1,1,1,1]])



MAXSIZE = 50
POSSIBLE_DIR = 8
input_maze_size = 8

maze = np.zeros((MAXSIZE,MAXSIZE))
start_location = Point(0,0)
end_location = Point(6,7)

# One-Padding maze
maze_size = input_maze_size + 2
# In python this is concatenation
start_location.x = start_location.x + 1
start_location.y = start_location.y + 1

end_location.x = end_location.x + 1
end_location.y = end_location.y + 1

for i in range(maze_size):
    for j in range(maze_size):
        if(i == 0) or (j == 0) or (i == maze_size-1) or (j == maze_size - 1):
            maze[i][j] = 1
        else:
            maze[i][j] = input_maze[i-1][j-1]
        


In [206]:
print(maze[:maze_size,:maze_size])
print(f"Start:{start_location.x},{start_location.y}")
print(f"End:{end_location.x},{end_location.y}")

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Start:1,1
End:7,8


# Create a possible_pos table for maze

In [207]:
class possible_pos:
    NORTH = [-1,0]
    NORTH_EAST = [-1,1]
    EAST = [0,1]
    SOUTH_EAST = [1,1]
    SOUTH  = [1,0]
    SOUTH_WEST = [1,-1]
    WEST = [0,-1]
    NORTH_WEST = [-1,-1]

In [208]:
dir = possible_pos()
dir.EAST

[0, 1]

In [209]:
import copy
mark = copy.deepcopy(maze)


print("Mark")
print(mark[:input_maze_size+2,:input_maze_size+2])

print("Maze")
print(maze[:input_maze_size+2,:input_maze_size+2])
print("maze(2,2)")
print(maze[2][2])


Mark
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Maze
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
maze(2,2)
0.0


# Traversing the maze

In [210]:
# Can simply use a list as a stack in python!
# Instatiating a stack
stack = []
stack == []
# stack.append(3)
# stack.append(7)
# stack
# stack == []
len(stack)
stack

[]

In [211]:
print(start_location.x)
print(start_location.y)

stack.append(start_location)

print(f"Length of stack:{len(stack)}")

for j in range(len(stack)):
    x_pos = stack[j].x
    y_pos = stack[j].y
    
    print(f"({x_pos},{y_pos})")
# Make sure that there is going to be one single element!
# Also you should reset or rerun clearing all blocks whenever you want to run a new block!
stack

1
1
Length of stack:1
(1,1)


In [212]:
POSSIBLE_DIR = 8
possible_pos = Point(0,0)
mark[start_location.x][start_location.y] = 1
maze[start_location.x][start_location.y] = 9
x_pos = 0
y_pos = 0
    
while(stack != []):
    current_pos = stack.pop()
        
    pos_x = current_pos.x
    pos_y = current_pos.y
    attempt = 0
    
    # print("---------------------------")
    # print("Maze")
    # print(f"Current position: ({pos_x},{pos_y})")
    
    # Traversing all possible possible_pos
    for i in range(POSSIBLE_DIR):
        if i == 0:
            possible_pos.x = dir.SOUTH[0]
            possible_pos.y = dir.SOUTH[1]
        elif i == 1:
            possible_pos.x = dir.SOUTH_WEST[0]
            possible_pos.y = dir.SOUTH_WEST[1]
        elif i == 2:
            possible_pos.x = dir.WEST[0]
            possible_pos.y = dir.WEST[1]
        elif i == 3:
            possible_pos.x = dir.NORTH_WEST[0]
            possible_pos.y = dir.NORTH_WEST[1]
        elif i == 4:
            possible_pos.x = dir.NORTH[0]
            possible_pos.y = dir.NORTH[1]
        elif i == 5:
            possible_pos.x = dir.NORTH_EAST[0]
            possible_pos.y = dir.NORTH_EAST[1]
        elif i == 6:
            possible_pos.x = dir.EAST[0]
            possible_pos.y = dir.EAST[1]
        elif i == 7:
            possible_pos.x = dir.SOUTH_EAST[0]
            possible_pos.y = dir.SOUTH_EAST[1]
        
        possible_pos.x = pos_x + possible_pos.x
        possible_pos.y = pos_y + possible_pos.y
        
        if(possible_pos.x == end_location.x and \
            possible_pos.y == end_location.y):
            print("End point reached")
            mark[possible_pos.x][possible_pos.y] = 1
            maze[possible_pos.x][possible_pos.y] = 9
            break
        
        # Push the next possible route into stack
        if(mark[possible_pos.x][possible_pos.y] != 1 and \
           maze[possible_pos.x][possible_pos.y] != 1):
            mark[possible_pos.x][possible_pos.y] = 1
            maze[possible_pos.x][possible_pos.y] = 9
            current_pos = possible_pos 
            stack.append(copy.deepcopy(possible_pos))
        else:
            attempt += 1
            
    if attempt == POSSIBLE_DIR:
        maze[current_pos.x][current_pos.y] = 0
                    
    # print("---------------------------")
    # print("Maze")
    # print(maze[:maze_size,:maze_size])
    # print("Mark")
    # print(mark[:maze_size,:maze_size])


            

End point reached


In [213]:
print("Maze")
print(maze[:maze_size,:maze_size])

print("Mark")
print(mark[:maze_size,:maze_size]) 


Maze
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 0. 1. 1. 0. 0. 9. 0. 1.]
 [1. 1. 9. 9. 9. 9. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 0. 9. 9. 9. 0. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 9. 9. 9. 9. 9. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Mark
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
